name: Continuos Deployment

on:
  workflow_dispatch:
    inputs:
      lambdas:
        description: "Names of the Lambdas to deploy (comma-separated)"
        required: false
        type: string
        options:
        - auth:signin
        - auth:signup
        default: "auth/signin,auth/signup"

jobs:
  manual-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Step 2: Configurar AWS Credenciais
    - uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-north-1'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/hydrogen

    # Step 3: Processar Lambdas passadas via input
    - name: Deploy Specified Lambdas
      run: |
        IFS=',' read -r -a LAMBDAS <<< "${{ github.event.inputs.lambdas }}"
        for lambda in "${LAMBDAS[@]}"; do
          echo "Processing Lambda: $lambda"

          cd $lambda
          npm ci

          # Criar .env
          echo "AWS_COGNITO_CLIENT_ID=${{ secrets.AWS_COGNITO_CLIENT_ID }}" > ./.env
          echo "AWS_COGNITO_CLIENT_SECRET=${{ secrets.AWS_COGNITO_CLIENT_SECRET }}" >> ./.env
          echo "AWS_COGNITO_REGION=eu-north-1" >> ./.env

          # Compactar arquivos
          zip -r lambda.zip ./*

          # Fazer deploy para AWS Lambda
          lambda_name="${lambda//\//-}"
          aws lambda update-function-code \
            --function-name=$lambda_name \
            --zip-file=fileb://lambda.zip

          cd ../..
        done
