name: Continuos Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  manual-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.SESSION_TOKEN }}
        aws-region: ${{ env.REGION_DEFAULT }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/hydrogen

    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/hydrogen

    - name: Get list of changed files
      id: changed-files
      run: |
        echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

    - name: Deploy Changed Lambdas
      run: |
        CHANGED_FILES="${{ steps.changed-files.outputs.files }}"
        LAMBDAS=("authorizer", "administrative" "customer-signin" "customer-signup")

        for lambda in "${LAMBDAS[@]}"; do
          if echo "$CHANGED_FILES" | grep -q "$lambda"; then
            echo "Deploying Lambda: $lambda"

            cd $lambda
            npm ci

            # Compactar arquivos
            zip -r lambda.zip ./*

            lambda_name="${lambda//\//-}"
            aws lambda update-function-code \
              --function-name=$lambda_name \
              --zip-file=fileb://lambda.zip

            cd - > /dev/null
          fi
        done